### ISSUE TITLE
clarifai_client_javascript

### ISSUE THREAD

**Issue by himanshu81494** [cassidoo/clarifai-javascript-starter#2]
Hi,
Inspired by this repo I made something similar and with more functions.
[https://github.com/himanshu81494/clarifai_client_javascript](url)
I want to improve it to make full feature client. Would you help? I am new to development.

**Comment by cassidoo** [comment]
Seems neat!  Made a couple issues there initially, I'll watch the repo and check it out as you work on it. :)
